# 以下为站点信息
site_name: 东北师大附中生存手册
site_url: https://ziyou-qinghua.github.io/

# 以下为仓库信息
repo_url: https://github.com/ziyou-qinghua/ziyou-qinghua.github.io/
repo_name: ziyou-qinghua/ziyou-qinghua.github.io/

# 以下为版权信息
copyright: '<p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"> Copyright &copy; 东北师大附中生存手册众编写人员. Some rights reserved: <a property="dct:title" rel="cc:attributionURL" href="https://ziyou-qinghua.github.io">东北师大附中生存手册</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>'

theme:
  language: zh
  name: material # 设定主题为 material
  custom_dir: overrides # 启用评论需要此行
  palette: #日夜模式切换
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple #基调色
      accent: green #强调色
      toggle:
        icon: material/weather-sunny
        name: 日间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple #基调色
      accent: red #强调色
      toggle:
        icon: material/weather-night
        name: 夜间模式
  icon:
    repo: fontawesome/brands/github # 设置git仓库图标
  
  features:
    - content.code.copy # 启用代码块复制按钮，尽管我觉得用不上
    - navigation.footer # 启用页尾上一页下一页按钮
    - navigation.instant # 内部链接即时加载
    - navigation.tabs # 页顶导航栏
    - navigation.tabs.sticky # 粘性导航栏
    - navigation.top # 回到顶部
    - toc.follow # 边栏自动滚动

markdown_extensions: # markdown扩展插件
  - admonition # 启用注释语法扩展
  - pymdownx.arithmatex: # 数学公式支持
      generic: true
  - pymdownx.caret # 下划线与上标
  - pymdownx.details # 启用注释语法扩展
  - pymdownx.mark # 强调
  - pymdownx.superfences # 启用注释语法扩展
  - pymdownx.tilde # 删除线与下标
  - meta #waline需要，参见https://github.com/squidfunk/mkdocs-material/discussions/4166

extra_css: #js文件
  - css/heimu.css # 黑幕功能实现

extra_javascript: #js文件
  - javascripts/mathjax.js # 数学公式支持
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # 数学公式支持

# 以下为目录信息
nav:
  - "index.md"
  - 前言:
    - "intro/docs.md"
    - "intro/notice.md"
    - "intro/thanks.md"
  - 日程安排:
    - "time/daily.md"
    - "time/lessons.md"
    - "time/test-and-exam.md"
    - "time/break.md"
    - "time/sat.md"
    - "time/extra-course.md"
    - "time/events.md"
    - "time/army.md"
  - 学校相关:
    - "school/uniform.md"
    - "school/card.md"
    - "school/ziyou.md"
    - "school/qinghua.md"
    - "school/map.md"
  - 分班及班型:
#   - "type/exam.md"
    - "type/num.md"
    - "type/gaokao.md"
    - "type/honor.md"
# - 硬件设备:
#   - "device/classroom.md"
  - 学生团体:
    - "team/orgnization.md"
    - "team/club.md"
    - "team/unofficial.md"
    - "team/rip.md"
# - 飞跃手册:
#   - "fly/gaokao.md"
#   - "fly/oh.md"
#   - "fly/overseas.md"
#   - "fly/olympic.md"
#   - "fly/art.md"
#   - "fly/physics.md"
# - 杂项:
  - 一条名为长庆街的河:
    - "changqing/goodbye.md"
    - "changqing/changqing2024.md" 
    - "changqing/changqing2025.md" 
  - 贡献:
    - "contribution/how.md"
    - markdown语法:
      - "contribution/grammar.md"
      - "contribution/extra-grammar.md"
    - "contribution/log.md"
  - "board.md"
